import PageShell from "@/components/PageShell";
import PageHero from "@/components/PageHero";
import { Section, SectionHeader, Callout, CTAButton } from "@/components/ui";

export const metadata = { title: "NRG Group Fitness Schedule" };

const classes = [
  { name: "Yoga Flow", intensity: "Low", duration: "60 min", desc: "Vinyasa-style flow linking breath and movement. All levels welcome." },
  { name: "Power Yoga", intensity: "Medium", duration: "60 min", desc: "Heat-building sequences focused on strength and flexibility." },
  { name: "Pilates Mat", intensity: "Medium", duration: "50 min", desc: "Core-centred mat work drawing on the classical Pilates repertoire." },
  { name: "HIIT / Bootcamp", intensity: "High", duration: "45 min", desc: "High-intensity intervals mixing bodyweight, dumbbells, and cardio bursts." },
  { name: "Cycle Studio", intensity: "High", duration: "45 min", desc: "Indoor cycling with intervals, sprints, and climbs. Studio Room 3216." },
  { name: "Strength & Sculpt", intensity: "Medium", duration: "55 min", desc: "Barbell and dumbbell circuit built around compound lifts." },
  { name: "Barre Fusion", intensity: "Medium", duration: "50 min", desc: "Ballet-inspired isometrics combined with Pilates and light cardio." },
  { name: "Zumba", intensity: "Medium", duration: "55 min", desc: "Dance-based cardio to Latin and world rhythms — no experience needed." },
  { name: "Aqua Fit", intensity: "Low", duration: "50 min", desc: "Water-based conditioning at the Gryphon Aquatic Centre." },
  { name: "Mobility & Mind", intensity: "Low", duration: "45 min", desc: "Guided mobility, myofascial release, and mindfulness. Post-training recovery focus." },
  { name: "Kettlebell Basics", intensity: "Medium", duration: "50 min", desc: "Foundational kettlebell technique — swings, cleans, presses, and Turkish get-ups." },
  { name: "Boxing Conditioning", intensity: "High", duration: "50 min", desc: "Non-contact boxing footwork, bag work, and conditioning circuits." },
];

const intensityColors = {
  Low: "bg-emerald-100 text-emerald-800",
  Medium: "bg-amber-100 text-amber-800",
  High: "bg-rose-100 text-rose-800",
} as const;

export default function NRGPage() {
  return (
    <PageShell>
      <PageHero
        eyebrow="Fitness & Wellness"
        title="NRG Group Fitness"
        subtitle="40+ weekly classes across strength, cardio, flexibility, and mind-body. All included with NRG Plus or Community NRG memberships. Drop-in and single-class options available for pass holders."
        imageSrc="/images/facilities/fitness-classes.jpg"
        imageAlt="NRG group fitness class"
        crumbs={[{ label: "NRG Schedule" }]}
      />

      <Section>
        <SectionHeader
          eyebrow="Class catalogue"
          title="Browse this term's offerings"
          subtitle="Class times rotate each Tuesday. Register in-app or drop in at Studio Rooms 3214, 3216, or the Group Fitness Studio."
        />

        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {classes.map((c) => (
            <div key={c.name} className="rounded-2xl border border-slate-200 bg-white p-6 hover:border-gryphon-red hover:shadow-md transition-all">
              <div className="flex items-start justify-between gap-3">
                <h3 className="text-lg font-bold text-slate-900">{c.name}</h3>
                <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded-full ${intensityColors[c.intensity as keyof typeof intensityColors]}`}>
                  {c.intensity}
                </span>
              </div>
              <div className="mt-1 text-xs text-slate-500 font-medium">{c.duration}</div>
              <p className="mt-3 text-sm text-slate-600 leading-relaxed">{c.desc}</p>
            </div>
          ))}
        </div>
      </Section>

      <section className="bg-slate-50 border-y border-slate-200">
        <div className="mx-auto max-w-7xl px-6 py-16">
          <div className="grid gap-8 md:grid-cols-2">
            <div>
              <div className="text-xs font-bold uppercase tracking-widest text-gryphon-red">Weekly calendar</div>
              <h2 className="mt-3 text-2xl font-bold text-slate-900">Updated every Tuesday</h2>
              <p className="mt-4 text-slate-600 leading-relaxed text-sm">
                The literal day/time/instructor grid is generated by our CONNECT registration
                system and updates each Tuesday for the following week. For today&apos;s schedule,
                check the Client Services front desk display or the NRG Calendar QR code posted at
                the entrance.
              </p>
            </div>
            <div>
              <div className="text-xs font-bold uppercase tracking-widest text-gryphon-red">How to attend</div>
              <h2 className="mt-3 text-2xl font-bold text-slate-900">Just show up</h2>
              <p className="mt-4 text-slate-600 leading-relaxed text-sm">
                With NRG Plus or Community NRG, no pre-registration is needed for most classes.
                Arrive 5–10 minutes early. High-demand classes (Cycle, Barre) may cap enrollment —
                arrive earlier or reserve at Client Services.
              </p>
            </div>
          </div>
        </div>
      </section>

      <Section>
        <Callout title="Not a member yet?">
          NRG classes require the <strong>NRG Plus</strong> student add-on ($55/semester) or a
          <strong> Community NRG</strong> monthly membership ($71.90/month). Single-class drop-ins
          are $12 for members, $18 for non-members.
        </Callout>
        <div className="mt-6 flex flex-wrap gap-3">
          <CTAButton href="/membership">Membership Options</CTAButton>
          <CTAButton href="/fitness/group-classes" variant="ghost">Group Class Details</CTAButton>
        </div>
      </Section>
    </PageShell>
  );
}
